replicaCount: 1

image:
  repository: docker.io/tusk03/golang-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: golang-app.local
      paths:
        - path: /
          pathType: Prefix

resources: {}
